# Generated by Django 4.2.2 on 2023-06-22 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursenotifications',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 41, 27, 841174)),
        ),
        migrations.AddField(
            model_name='forumnotifications',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 41, 27, 841174)),
        ),
    ]
