# Generated by Django 4.2.2 on 2023-06-23 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_delete_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='forum',
        ),
        migrations.AlterField(
            model_name='notification',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 15, 36, 59, 109958)),
        ),
    ]
