# Generated by Django 4.2.2 on 2023-06-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_student_delete_userprofile'),
        ('instructorDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorDashboard.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.student')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_students',
            field=models.ManyToManyField(related_name='assigned_assignments', through='instructorDashboard.AssignedAssignment', to='signup.student'),
        ),
    ]
