# Generated by Django 4.2.2 on 2023-06-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorDashboard', '0003_alter_submittedassignment_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
