# Generated by Django 4.2.2 on 2023-06-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_student_delete_userprofile'),
        ('instructorDashboard', '0004_alter_assignment_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submittedassignment',
            unique_together={('student', 'assignment')},
        ),
    ]
