# Generated by Django 4.2.2 on 2023-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_student_delete_userprofile'),
        ('instructorDashboard', '0005_alter_submittedassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='signup.student'),
        ),
    ]
