# Generated by Django 4.2.2 on 2023-06-22 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_alter_post_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 5, 35, 56735)),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 12, 5, 35, 56213)),
        ),
    ]
