# Generated by Django 4.2.2 on 2023-06-22 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_reply_uploadtime_alter_post_uploadtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 40, 32, 568674)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='uploadTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 19, 40, 32, 568674)),
        ),
    ]
